project_id = "hdbhzrtmfjbwqyketpbo"

[functions.agentgpt-chat]
verify_jwt = false

[functions.agentgpt-stream]
verify_jwt = false

[functions.repliers-search]
verify_jwt = false

[functions.property-analysis]
verify_jwt = false

[functions.zillow-search]
verify_jwt = false

[functions.scrape-property-link]
verify_jwt = false
